name: health_connector
description: Health connector.ai is health and fitness app powered by Livvinyl progressive media marketing.

publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # google_ml_kit: ^0.7.3
  camera: ^0.9.4+19
  firebase_messaging: ^11.2.5
  firebase_core: ^1.11.0
  firebase_database: ^9.0.20
  permission_handler: ^9.2.0
  flutter_tts: ^3.2.3
  google_fonts: ^2.1.0
  firebase_auth: ^3.3.13
  animated_button: ^0.2.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.11
  image_picker: ^0.8.4+4
  dropdown_search: ^2.0.1
  google_sign_in: ^5.2.3
  sign_in_with_apple: ^3.3.0
  connectivity_plus: ^2.3.6+1
  flutter_launcher_icons: ^0.9.2
  octo_image: ^1.0.1
  blurhash_dart: ^1.1.0
  image: ^3.1.3
  firebase_storage: ^10.2.12
  circular_countdown_timer: ^0.2.2
  persistent_bottom_nav_bar: ^4.0.2
  google_mlkit_pose_detection: ^0.3.0
  google_mlkit_translation: ^0.3.0
  flutter_cache_manager: ^3.3.0
  agora_uikit: ^1.0.2
  agora_rtc_engine: ^5.3.0
  flutter_firebase_chat_core: ^1.6.3
  file_picker: ^4.6.0
  flutter_chat_ui: ^1.6.4
  mime: ^1.0.2
  open_file: ^3.2.1
  loading_overlay: ^0.3.0
  share_plus: ^4.0.10
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  syncfusion_flutter_charts: ^20.1.61
  fl_chart: ^0.55.0
  font_awesome_flutter: ^10.1.0
  native_ar_viewer: ^0.0.1
  flutter_downloader: ^1.8.0+1
  quick_look: ^0.0.4
  video_player: ^2.4.5
  awesome_notifications: ^0.6.21
  flutter_rating_bar: ^4.0.1
  native_screenshot: #^1.0.0
    path: ../native_screenshot
  native_device_orientation: ^1.1.4
  connectycube_flutter_call_kit: ^2.0.6
  provider: ^6.0.3
  flutter_bloc: ^8.1.1


flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/logo.png" # only available for Android 8.0 devices and above

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/social/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

