name: health_connector
description: Health connector.ai is health and fitness app powered by Livvinyl progressive media marketing.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # google_ml_kit: ^0.7.3
  camera: ^0.9.7
  firebase_messaging: ^11.4.0
  firebase_core: ^1.17.0
  firebase_database: ^9.0.14
  permission_handler: ^9.2.0
  flutter_tts: ^3.3.3
  google_fonts: ^3.0.1
  firebase_auth: ^3.3.18
  animated_button: ^0.2.0
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  dropdown_search: ^4.0.1
  google_sign_in: ^5.3.2
  sign_in_with_apple: ^4.0.0
  flutter_facebook_auth: ^4.3.4
  connectivity_plus: ^2.2.0
  flutter_launcher_icons: ^0.9.2
  octo_image: ^1.0.2
  blurhash_dart: ^1.1.0
  image: ^3.1.3
  firebase_storage: ^10.2.16
  circular_countdown_timer: ^0.2.1
  persistent_bottom_nav_bar: ^4.0.2
  # google_mlkit_pose_detection: ^0.3.0
  google_mlkit_pose_detection:
    git:
      ref: a30744eee1d1b1f601e0dd5ce7f201ba377e1c64
      path: packages/google_mlkit_pose_detection
      url: https://github.com/sikandernoori/Google-Ml-Kit-plugin
  google_mlkit_translation:
    git:
      ref: d3abcc432c7e85dd32185be9be0b9db063bcc970
      path: packages/google_mlkit_translation
      url: https://github.com/sikandernoori/Google-Ml-Kit-plugin
  model_viewer: ^0.8.1
  flutter_cache_manager: ^3.3.0


flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/logo.png" # only available for Android 8.0 devices and above

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/social/
    - assets/ahi_assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

